version: '3.7'

services:
  raft-server1:
    container_name: raft-server1
    hostname: raft-server1
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - SERVER_ID=raft-server1
      - GRPC_PORT=5051
      - EXPOSED_HTTP_PORT=6051
      - SERVERS_INFO_JSON=[]
      - ELECTION_TIMEOUT_FROM_MS=10000
      - ELECTION_TIMEOUT_TO_MS=15000
      - HEARTBEAT_INTERVAL_MS=1000

  raft-server2:
    container_name: raft-server2
    hostname: raft-server2
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - SERVER_ID=raft-server2
      - GRPC_PORT=5051
      - EXPOSED_HTTP_PORT=6051
      - SERVERS_INFO_JSON=[]
      - ELECTION_TIMEOUT_FROM_MS=10000
      - ELECTION_TIMEOUT_TO_MS=15000
      - HEARTBEAT_INTERVAL_MS=1000

  raft-server3:
    container_name: raft-server3
    hostname: raft-server3
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - SERVER_ID=raft-server3
      - GRPC_PORT=5051
      - EXPOSED_HTTP_PORT=6051
      - SERVERS_INFO_JSON=[]
      - ELECTION_TIMEOUT_FROM_MS=10000
      - ELECTION_TIMEOUT_TO_MS=15000
      - HEARTBEAT_INTERVAL_MS=1000