version: '3.7'

services:
  raft-server1:
    container_name: raft-server1
    hostname: raft-server1
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 6051:6050
    environment:
      - SERVER_ID=raft-server1
      - GRPC_PORT=5051
      - EXPOSED_HTTP_PORT=6050
      - SERVERS_INFO_JSON=[]
      - ELECTION_TIMEOUT_FROM_MS=10000
      - ELECTION_TIMEOUT_TO_MS=20000
      - HEARTBEAT_INTERVAL_MS=3000
    networks:
      raft-network:
        aliases:
          - raft-server1
      raft-network-internal:
        ipv4_address: 10.10.0.11

  raft-server2:
    container_name: raft-server2
    hostname: raft-server2
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 6052:6050
    environment:
      - SERVER_ID=raft-server2
      - GRPC_PORT=5051
      - EXPOSED_HTTP_PORT=6050
      - SERVERS_INFO_JSON=[]
      - ELECTION_TIMEOUT_FROM_MS=10000
      - ELECTION_TIMEOUT_TO_MS=20000
      - HEARTBEAT_INTERVAL_MS=3000
    networks:
      raft-network:
        aliases:
          - raft-server2
      raft-network-internal:
        ipv4_address: 10.10.0.12

  raft-server3:
    container_name: raft-server3
    hostname: raft-server3
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 6053:6050
    environment:
      - SERVER_ID=raft-server3
      - GRPC_PORT=5051
      - EXPOSED_HTTP_PORT=6050
      - SERVERS_INFO_JSON=[]
      - ELECTION_TIMEOUT_FROM_MS=10000
      - ELECTION_TIMEOUT_TO_MS=20000
      - HEARTBEAT_INTERVAL_MS=3000
    networks:
      raft-network:
        aliases:
          - raft-server3
      raft-network-internal:
        ipv4_address: 10.10.0.13

networks:
    raft-network:
      name: raft-network
    raft-network-internal:
      name: raft-network-internal
      internal: true
      ipam:
        driver: default
        config:
          - subnet: 10.10.0.0/16
            gateway: 10.10.0.1