version: '3.7'

services:
  raft-server:
    container_name: raft-server
    hostname: raft-server
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - KFTI_INPUT_FILE_NAME=data/RC_2010-12
    volumes:
      - ./data:/data
